<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace zostay\Speakeasy_API\Models\Operations;

use \zostay\Speakeasy_API\Utils\SpeakeasyMetadata;
/**
 * GetApisOp - Configuration for filter operations
 * 
 * @package zostay\Speakeasy_API\Models\Operations
 * @access public
 */
class GetApisOp
{
    /**
     * Whether to AND or OR the filters
     * 
     * @var bool $and
     */
	#[SpeakeasyMetadata('queryParam:name=and')]
    public bool $and;
    
	public function __construct()
	{
		$this->and = false;
	}
}
