<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace zostay\Speakeasy_API\Models\Operations;


class GetAllForVersionApiEndpointsResponse
{
    /**
     * OK
     * 
     * @var ?array<\zostay\Speakeasy_API\Models\Shared\ApiEndpoint> $apiEndpoints
     */
	
    public ?array $apiEndpoints = null;
    
	
    public string $contentType;
    
    /**
     * Default error response
     * 
     * @var ?\zostay\Speakeasy_API\Models\Shared\Error $error
     */
	
    public ?\zostay\Speakeasy_API\Models\Shared\Error $error = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->apiEndpoints = null;
		$this->contentType = "";
		$this->error = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
