<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace zostay\Speakeasy_API\Models\Operations;

use \zostay\Speakeasy_API\Utils\SpeakeasyMetadata;
class GetEmbedAccessTokenRequest
{
    /**
     * The description of the embed access token.
     * 
     * @var ?string $description
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=description')]
    public ?string $description = null;
    
    /**
     * The duration (in minutes) of the embed access token.
     * 
     * @var ?int $duration
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=duration')]
    public ?int $duration = null;
    
    /**
     * The filter to apply to the query.
     * 
     * @var ?\zostay\Speakeasy_API\Models\Shared\Filters $filters
     */
	#[SpeakeasyMetadata('queryParam:serialization=json,name=filters')]
    public ?\zostay\Speakeasy_API\Models\Shared\Filters $filters = null;
    
	public function __construct()
	{
		$this->description = null;
		$this->duration = null;
		$this->filters = null;
	}
}
