<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace zostay\Speakeasy_API\Models\Operations;

use \zostay\Speakeasy_API\Utils\SpeakeasyMetadata;
class QueryEventLogRequest
{
    /**
     * The filter to apply to the query.
     * 
     * @var ?\zostay\Speakeasy_API\Models\Shared\Filters $filters
     */
	#[SpeakeasyMetadata('queryParam:serialization=json,name=filters')]
    public ?\zostay\Speakeasy_API\Models\Shared\Filters $filters = null;
    
	public function __construct()
	{
		$this->filters = null;
	}
}
