<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace zostay\Speakeasy_API\Models\Shared;


/**
 * Error - The `Status` type defines a logical error model
 * 
 * @package zostay\Speakeasy_API\Models\Shared
 * @access public
 */
class Error
{
    /**
     * A developer-facing error message.
     * 
     * @var string $message
     */
	#[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $message;
    
    /**
     * The HTTP status code
     * 
     * @var int $statusCode
     */
	#[\JMS\Serializer\Annotation\SerializedName('status_code')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $statusCode;
    
	public function __construct()
	{
		$this->message = "";
		$this->statusCode = 0;
	}
}
