<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace zostay\Speakeasy_API\Models\Shared;


/**
 * GenerateOpenApiSpecDiff - OK
 * 
 * @package zostay\Speakeasy_API\Models\Shared
 * @access public
 */
class GenerateOpenApiSpecDiff
{
	#[\JMS\Serializer\Annotation\SerializedName('current_schema')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $currentSchema;
    
	#[\JMS\Serializer\Annotation\SerializedName('new_schema')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $newSchema;
    
	public function __construct()
	{
		$this->currentSchema = "";
		$this->newSchema = "";
	}
}
