<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace zostay\Speakeasy_API\Models\Shared;


/**
 * Schema - A Schema represents an API schema for a particular Api and Version.
 * 
 * @package zostay\Speakeasy_API\Models\Shared
 * @access public
 */
class Schema
{
    /**
     * The ID of the Api this Schema belongs to.
     * 
     * @var string $apiId
     */
	#[\JMS\Serializer\Annotation\SerializedName('api_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $apiId;
    
    /**
     * Creation timestamp.
     * 
     * @var \DateTime $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
    /**
     * A detailed description of the Schema.
     * 
     * @var string $description
     */
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $description;
    
    /**
     * An ID referencing this particular revision of the Schema.
     * 
     * @var string $revisionId
     */
	#[\JMS\Serializer\Annotation\SerializedName('revision_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $revisionId;
    
    /**
     * The version ID of the Api this Schema belongs to.
     * 
     * @var string $versionId
     */
	#[\JMS\Serializer\Annotation\SerializedName('version_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $versionId;
    
    /**
     * The workspace ID this Schema belongs to.
     * 
     * @var string $workspaceId
     */
	#[\JMS\Serializer\Annotation\SerializedName('workspace_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $workspaceId;
    
	public function __construct()
	{
		$this->apiId = "";
		$this->createdAt = new \DateTime();
		$this->description = "";
		$this->revisionId = "";
		$this->versionId = "";
		$this->workspaceId = "";
	}
}
