<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace zostay\Speakeasy_API\Models\Shared;


/**
 * SchemaDiff - A SchemaDiff represents a diff of two Schemas.
 * 
 * @package zostay\Speakeasy_API\Models\Shared
 * @access public
 */
class SchemaDiff
{
    /**
     * Holds every addition change in the diff.
     * 
     * @var array<string> $additions
     */
	#[\JMS\Serializer\Annotation\SerializedName('additions')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    public array $additions;
    
    /**
     * Holds every deletion change in the diff.
     * 
     * @var array<string> $deletions
     */
	#[\JMS\Serializer\Annotation\SerializedName('deletions')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    public array $deletions;
    
    /**
     * Holds every modification change in the diff.
     * 
     * @var array<string, \zostay\Speakeasy_API\Models\Shared\SchemaDiffValueChange> $modifications
     */
	#[\JMS\Serializer\Annotation\SerializedName('modifications')]
    #[\JMS\Serializer\Annotation\Type('array<string, zostay\Speakeasy_API\Models\Shared\SchemaDiffValueChange>')]
    public array $modifications;
    
	public function __construct()
	{
		$this->additions = [];
		$this->deletions = [];
		$this->modifications = [];
	}
}
