<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace zostay\Speakeasy_API\Models\Shared;


/**
 * UnboundedRequest - An UnboundedRequest represents the HAR content capture by Speakeasy when logging a request.
 * 
 * @package zostay\Speakeasy_API\Models\Shared
 * @access public
 */
class UnboundedRequest
{
    /**
     * Creation timestamp.
     * 
     * @var \DateTime $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
    /**
     * The HAR content of the request.
     * 
     * @var string $har
     */
	#[\JMS\Serializer\Annotation\SerializedName('har')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $har;
    
    /**
     * The size of the HAR content in bytes.
     * 
     * @var int $harSizeBytes
     */
	#[\JMS\Serializer\Annotation\SerializedName('har_size_bytes')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $harSizeBytes;
    
    /**
     * The ID of this request.
     * 
     * @var string $requestId
     */
	#[\JMS\Serializer\Annotation\SerializedName('request_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $requestId;
    
    /**
     * The workspace ID this request was made to.
     * 
     * @var string $workspaceId
     */
	#[\JMS\Serializer\Annotation\SerializedName('workspace_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $workspaceId;
    
	public function __construct()
	{
		$this->createdAt = new \DateTime();
		$this->har = "";
		$this->harSizeBytes = 0;
		$this->requestId = "";
		$this->workspaceId = "";
	}
}
