<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace zostay\Speakeasy_API\Models\Shared;


/**
 * VersionMetadata - A set of keys and associated values, attached to a particular version of an Api.
 * 
 * @package zostay\Speakeasy_API\Models\Shared
 * @access public
 */
class VersionMetadata
{
    /**
     * The ID of the Api this Metadata belongs to.
     * 
     * @var string $apiId
     */
	#[\JMS\Serializer\Annotation\SerializedName('api_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $apiId;
    
    /**
     * Creation timestamp.
     * 
     * @var \DateTime $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
    /**
     * The key for this metadata.
     * 
     * @var string $metaKey
     */
	#[\JMS\Serializer\Annotation\SerializedName('meta_key')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $metaKey;
    
    /**
     * One of the values for this metadata.
     * 
     * @var string $metaValue
     */
	#[\JMS\Serializer\Annotation\SerializedName('meta_value')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $metaValue;
    
    /**
     * The version ID of the Api this Metadata belongs to.
     * 
     * @var string $versionId
     */
	#[\JMS\Serializer\Annotation\SerializedName('version_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $versionId;
    
    /**
     * The workspace ID this Metadata belongs to.
     * 
     * @var string $workspaceId
     */
	#[\JMS\Serializer\Annotation\SerializedName('workspace_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $workspaceId;
    
	public function __construct()
	{
		$this->apiId = "";
		$this->createdAt = new \DateTime();
		$this->metaKey = "";
		$this->metaValue = "";
		$this->versionId = "";
		$this->workspaceId = "";
	}
}
